### ISSUE TITLE
Regression 1.7.3 to 1.7.4: __nccwpck_require__ is not defined

### ISSUE THREAD

**Issue by vieira** [vercel/webpack-asset-relocator-loader#188]
After updating from `@vercel/webpack-asset-relocator-loader` 1.7.3 to 1.7.4 the build still succeeds but the generated bundle now fails to start with the following error:

```
/Users/.../dist/index.js:198193
const googleProtoFilesDir = __nccwpck_require__.ab + "protos";
                            ^

ReferenceError: __nccwpck_require__ is not defined
    at 38020 (/Users/.../api/dist/index.js:198193:29)
    at __webpack_require__ (/Users/.../dist/index.js:774516:42)
    at 52013 (/Users/.../api/dist/index.js:198899:16)
    at __webpack_require__ (/Users/.../dist/index.js:774516:42)
    at new LanguageServiceClient (/Users/.../dist/index.js:50263:27)
    at 80046 (/Users/.../dist/index.js:661168:16)
    at __webpack_require__ (/Users/.../dist/index.js:774516:42)
    at 49801 (/Users/.../dist/index.js:661353:38)
    at __webpack_require__ (/Users/.../dist/index.js:774516:42)
    at 96739 (/Users/.../dist/index.js:660922:49)
```

Relevant webpack configuration:

```js
const webpack = require('webpack');

module.exports = {
  entry: './index.js',
  target: 'node20',
  node: false,
  devtool: false,
  resolve: {
    mainFields: ['main', 'module'],
  },
  // ...
  optimization: {
    minimize: false,
  },
  module: {
    rules: [
      {
        test: /\.mjs$/,
        type: 'javascript/auto',
      },
      {
        test: /\.m?js?$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: { rootMode: 'upward' },
        },
      },
      {
        test: /\.(m?js|node)$/,
        parser: { amd: false },
        use: {
          loader: '@vercel/webpack-asset-relocator-loader',
          options: {},
        },
      },
    ],
  },
  stats: {
    warnings: false,
  },
}
```

Downgrading to 1.7.3 fixes the issue, without any other changes.

**Comment by hotlif** [comment]
I have submitted a fix

You can also do the following as a temporary fix

```
npm install  --save-dev @vercel/ncc
```

**Comment by linonetwo** [comment]
Thank you! Downgrade to @vercel/webpack-asset-relocator-loader 1.7.3 fix this for me, thank you for posting this issue so I can google here!

**Comment by joncamp** [comment]
Is this being actively worked on? I see the October 8 fix has been sitting for a few months on the linux build not passing.

**Comment by ArrayIterator** [comment]
no update?

**Comment by wvanderdeijl** [comment]
@styfle or @guybedford has there been any progress on this issue? We have also downgraded back to 1.7.3 due to this.

**Comment by styfle** [comment]
@wvanderdeijl There's a PR started here but its failing CI

- https://github.com/vercel/webpack-asset-relocator-loader/pull/193

Feel free to fix it.
